-- Create Users table
create table public.users (
  fid bigint primary key,
  wallet_address text,
  xp bigint default 0,
  streak_days int default 0,
  last_active timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

-- Create Puzzles table
create table public.puzzles (
  id bigint primary key, -- Matches contract ID
  price bigint not null, -- In wei/USDC units
  total_pieces int not null,
  pieces_minted_count int default 0,
  is_complete boolean default false,
  image_url text, -- Revealed image
  solution_hash text,
  created_at timestamp with time zone default now()
);

-- Create Mints table
create table public.mints (
  tx_hash text primary key,
  puzzle_id bigint references public.puzzles(id),
  piece_id int not null,
  user_fid bigint references public.users(fid),
  minter_address text not null,
  created_at timestamp with time zone default now(),
  unique(puzzle_id, piece_id)
);

-- Create XP History table
create table public.xp_history (
  id bigint generated by default as identity primary key,
  user_fid bigint references public.users(fid),
  amount int not null,
  reason text not null,
  created_at timestamp with time zone default now()
);

-- Create Leaderboard View
create view public.leaderboard as
select
  fid,
  wallet_address,
  xp,
  streak_days
from public.users
order by xp desc;

-- RLS Policies (Enable RLS)
alter table public.users enable row level security;
alter table public.puzzles enable row level security;
alter table public.mints enable row level security;
alter table public.xp_history enable row level security;

-- Public read access
create policy "Public read access" on public.users for select using (true);
create policy "Public read access" on public.puzzles for select using (true);
create policy "Public read access" on public.mints for select using (true);
create policy "Public read access" on public.xp_history for select using (true);

-- Service role write access (for Edge Functions)
-- Note: Service role bypasses RLS, but explicit policies can be added if needed.
