-- Migration: V11 Schema Update
-- Description: Adds tables for Seasons, Monthly Events, Mystery Boxes, and Badges

-- 1. Seasons Table
create table public.seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  is_active boolean default false,
  created_at timestamp with time zone default now()
);

-- 2. Season XP / Leaderboard (Tracks XP per season for Top 10)
create table public.season_xp (
  season_id bigint references public.seasons(id),
  user_id bigint references public.users(id),
  xp_amount bigint default 0,
  updated_at timestamp with time zone default now(),
  primary key (season_id, user_id)
);

-- 3. Monthly Events / Tiers (Tracks monthly progress)
create table public.monthly_events (
  id bigint generated by default as identity primary key,
  month_date date not null, -- First day of the month (e.g., '2025-12-01')
  user_id bigint references public.users(id),
  xp_gained bigint default 0,
  tier text check (tier in ('Bronze', 'Silver', 'Gold', 'Diamond')),
  updated_at timestamp with time zone default now(),
  unique(month_date, user_id)
);

-- 4. Mystery Boxes
create table public.mystery_boxes (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id),
  box_type text check (box_type in ('Common', 'Rare', 'Epic', 'Legendary')),
  status text default 'locked' check (status in ('locked', 'ready', 'opened')),
  reward_amount bigint,
  reward_type text, -- 'XP', 'USDC', 'BADGE'
  created_at timestamp with time zone default now(),
  opened_at timestamp with time zone
);

-- 5. Badges (Metadata and User tracking)
create table public.badges (
  id text primary key, -- e.g., 'sniper_king', 'early_adopter'
  name text not null,
  description text,
  image_url text,
  tier text check (tier in ('Bronze', 'Silver', 'Gold', 'Diamond', 'Special')),
  created_at timestamp with time zone default now()
);

create table public.user_badges (
  user_id bigint references public.users(id),
  badge_id text references public.badges(id),
  earned_at timestamp with time zone default now(),
  primary key (user_id, badge_id)
);

-- 6. Sniper Logs (Off-chain tracking for notifications/history)
create table public.sniper_logs (
  id bigint generated by default as identity primary key,
  puzzle_id bigint references public.puzzles(id),
  user_id bigint references public.users(id),
  snipe_time timestamp with time zone default now(),
  duration_held interval,
  was_successful boolean default false
);

-- Enable RLS
alter table public.seasons enable row level security;
alter table public.season_xp enable row level security;
alter table public.monthly_events enable row level security;
alter table public.mystery_boxes enable row level security;
alter table public.badges enable row level security;
alter table public.user_badges enable row level security;
alter table public.sniper_logs enable row level security;

-- Policies (Public Read for most, specific logic can be added later)
create policy "Public read access" on public.seasons for select using (true);
create policy "Public read access" on public.season_xp for select using (true);
create policy "Public read access" on public.monthly_events for select using (true);
create policy "Public read access" on public.badges for select using (true);
create policy "Public read access" on public.user_badges for select using (true);
create policy "Public read access" on public.sniper_logs for select using (true);

-- Mystery Boxes: Users can see their own
create policy "Users can see own boxes" on public.mystery_boxes for select using (true); 
-- Note: In a real app with Auth, we'd restrict this. For now, keeping it open or matching `users` table logic.
